name: CI - Build and Test

on:
  pull_request:
    branches: [ master ]

jobs:
  build-net6:
    runs-on: ubuntu-latest
    name: Pipeline
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build ShapeCrawler/ShapeCrawler.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test --configuration Release --no-restore --verbosity normal -f net7.0
  build-net48:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Framework 4.8
        run: |
          choco install netfx-4.8 -y
      - name: Restore packages
        run: nuget restore
      - name: Build
        run: msbuild /p:Configuration=Release
      - name: Run tests
        run: vstest.console.exe /p:Platform=x86 /p:Configuration=Release **/*.Tests.dll
