name: Test

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      
      - name: Restore packages
        run: dotnet restore
      
      - name: Build
        run: dotnet build ShapeCrawler/ShapeCrawler.csproj --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal -f net7.0